#!/usr/bin/env python3
"""Generate rnsd's own config file from local.yaml's reticulum: section.

Run as rnsd.service's own ExecStartPre, before rnsd itself starts --
this is the ONE place the RNode's serial port and radio parameters
live (config.reticulum.rnode_*), so rnsd needs a freshly-written config
every time those change, same as concentrator_config.py regenerates
the SX1302 HAL config from local.yaml on every meshpoint boot rather
than expecting hand edits.

Always overwrites the whole file -- like node_config.h (the Reticulum
companion firmware card's own generated file), this is a generated
artifact, not something to hand-edit alongside. Written into
config.reticulum.reticulum_config_dir -- the SAME directory
src/reticulum/lxmf_service.py points meshpoint's own RNS client at.
They MUST share this directory: the shared-instance RPC channel
authenticates per-configdir (confirmed live -- meshpoint's own client
using a different configdir than rnsd produced a real, reproducible
"digest received was wrong" RPC error; see config.py's ReticulumConfig
docstring for the full story), so this being the same path is what
actually makes the client/master split work, not just a convenience.

Usage (invoked by rnsd.service, WorkingDirectory=/opt/meshpoint):
    python3 scripts/write_rnsd_config.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import load_config  # noqa: E402

_TEMPLATE = """\
# Generated by scripts/write_rnsd_config.py from local.yaml's
# reticulum: section -- do not edit manually, changes will be
# overwritten on the next rnsd.service start.

[reticulum]
  enable_transport = True
  share_instance = Yes
  instance_name = default

[logging]
  loglevel = 4

[interfaces]

  [[Default Interface]]
    type = AutoInterface
    enabled = Yes
{rnode_block}
  [[ReticulumNet Internet]]
    type = TCPClientInterface
    enabled = Yes
    target_host = {backbone_host}
    target_port = {backbone_port}
"""

_RNODE_TEMPLATE = """
  [[RNode LoRa]]
    type = RNodeInterface
    enabled = Yes
    port = {rnode_serial_port}

    frequency = {rnode_frequency_hz}
    bandwidth = {rnode_bandwidth_hz}
    txpower = {rnode_tx_power}
    spreadingfactor = {rnode_spreading_factor}
    codingrate = {rnode_coding_rate}
"""


def main() -> int:
    cfg = load_config()
    rc = cfg.reticulum

    config_dir = Path(rc.reticulum_config_dir)
    config_dir.mkdir(parents=True, exist_ok=True)

    rnode_block = ""
    if rc.rnode_serial_port:
        rnode_block = _RNODE_TEMPLATE.format(
            rnode_serial_port=rc.rnode_serial_port,
            rnode_frequency_hz=rc.rnode_frequency_hz,
            rnode_bandwidth_hz=rc.rnode_bandwidth_hz,
            rnode_tx_power=rc.rnode_tx_power,
            rnode_spreading_factor=rc.rnode_spreading_factor,
            rnode_coding_rate=rc.rnode_coding_rate,
        )
    else:
        print(
            "reticulum.rnode_serial_port is not set -- writing a config "
            "with no RNode interface (TCP backbone only)."
        )

    content = _TEMPLATE.format(
        rnode_block=rnode_block,
        backbone_host=rc.backbone_host,
        backbone_port=rc.backbone_port,
    )

    config_path = config_dir / "config"
    config_path.write_text(content)
    print(f"Wrote {config_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
